[package]
name = "rust_explore_genpdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genpdf = "0.2.0"
lopdf = "0.31.0"
printpdf = "0.6.0"
